- README.md
> adding citation from Mary

- CMakeLists.txt
- ccpp/micm/micm.F90
- packaging/CMakeLists.txt
- packaging/modulefile.lua.in
- test/ccpp/integration/CMakeLists.txt
- test/ccpp/unit/micm.F90
Updates cmake to add an option to install mod files
Documented in this [google file](https://docs.google.com/document/d/11jaNz7a4ocoFEubiRzM6Vyim2z2i4r16Iihqpmme2PA/edit?usp=sharing)
> Create an environment module for MUSICA

- CITATION.cff
- fortran/test/fetch_content_integration/CMakeLists.txt
> adding citation file

- .github/workflows/docker.yml
- .github/workflows/mac.yml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
- .gitignore
- CMakeLists.txt
- python/CMakeLists.txt
- python/micm_test.py
- python/wrapper.cpp
- setup.py
- src/micm/micm.cpp
- Uses the [setup.py](https://github.com/pybind/cmake_example/tree/master) from the pybind11 cmake example
- Adds the python test to the suite of cmake tests so that they can be run from any computer
Instructions
*Installing the musica python package*
```
mkdir build
cd build
pip install -e ..
```
*Building and testing with cmake*
```
mkdir build
cd build
cmake -DMUSICA_ENABLE_PYTHON_LIBRARY=ON ..
make
make test ARGS=--verbose
```
> Fix the python build that I broke

- fortran/packaging/CMakeLists.txt
- src/packaging/CMakeLists.txt
Updates the packaging script to (hopefully) include TUV-x correctly
> Fix packaging script

- docker/Dockerfile.fortran-intel
> fixing intel

- .github/workflows/clang_tidy.yml
> Add GH action for clang-tidy

- CITATION.cff
- CMakeLists.txt
- cmake/dependencies.cmake
> Update the version to v0.7.0

- .github/workflows/mac.yml
> removing gcc 11

- fortran/test/fetch_content_integration/test_tuvx_api.F90
- fortran/tuvx/grid.F90
- include/musica/tuvx/grid.hpp
- src/test/unit/tuvx/tuvx_c_api.cpp
- src/tuvx/grid.cpp
- src/tuvx/interface_grid.F90
Adds the ability to return the number of sections in a grid
> Allow querying of grid size

- .github/workflows/format-python.yml
- .github/workflows/python-tests.yml
- .github/workflows/windows.yml
> 97 modify windows GitHub action to build and test the fortran code

- docs/source/conf.py
- docs/source/getting_started/overview.rst
Closes #245 
grep only shows mentions of NCAR in our docs. All other mentions are in URLs for repositories
> adding NSF prefix to NCAR in the docs

- .github/workflows/close_stale_issues.yml
added the workflow to auto close stale issues
closes #274
> added workflow to auto close stale issues

- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
- CITATION.cff
- CMakeLists.txt
- cmake/dependencies.cmake
- include/musica/micm/micm.hpp
- include/musica/micm/state.hpp
> Update the version

- CMakeLists.txt
- cmake/dependencies.cmake
Updating mechanism configuration version and bumping version to create a patch release
> updating mechanism configuration version

- src/packaging/modulefile.lua.in
Updates the lua script for environment module creation to properly set the environment variables for include and library paths
> Update modules configuration

- fortran/micm/CMakeLists.txt
- fortran/micm/micm.F90
- fortran/micm/state.F90
- fortran/test/fetch_content_integration/test_micm_api.F90
- fortran/test/fetch_content_integration/test_micm_box_model.F90
- include/musica/micm/state.hpp
- src/micm/micm.cpp
- src/micm/state.cpp
Interface for Fortran 
closes #273
> Interface fortran 273

- docker/Dockerfile
- docker/Dockerfile.fortran-gcc
- docker/Dockerfile.fortran-gcc.integration
- docker/Dockerfile.fortran-intel
- docker/Dockerfile.fortran-nvhpc
- docker/Dockerfile.memcheck
- docker/Dockerfile.mpi
- docker/Dockerfile.mpi_openmp
- docker/Dockerfile.openmp
- fortran/CMakeLists.txt
Removed JSON installation in the Docker scripts.
Note: Looks like packaging is broken, but this PR is unrelated.
> Remove JSON installation

- .github/workflows/docker_and_coverage.yml
- CMakeLists.txt
- README.md
- cmake/CodeCoverage.cmake
- docker/Dockerfile.coverage
This PR includes the code coverage dockerfile and action triggers to correctly get the code coverage for the project
closes #296
> Added Code Coverage

- musica/test/test_analytical.py
- musica/types.py
- musica/wrapper.cpp
- src/micm/state_c_interface.cpp
Updates the Python API to set state data in-place and avoid having to specify all species/parameters when updating the state.
> Update python state

- fortran/test/unit/util.F90
- fortran/util.F90
Adds copy assignment for `mappings_t` objects.
> Add copy assign for mappings

- .github/workflows/gh_pages.yml
- docker/Dockerfile.docs
- docs/source/_static/switcher.json
- docs/source/conf.py
Versions were not populated in the dropdown menu of the version.
closes #263
> Fix version selector in Documentation

- .github/workflows/python-wheels.yml
- CMakeLists.txt
- musica/tools/repair_wheel_gpu.sh
- pyproject.toml
Supported versions can be found [here](https://devguide.python.org/versions/)
> using supported python versions

- CMakeLists.txt
- musica/tools/repair_wheel_gpu.sh
- pyproject.toml
* using supported python versions
* repairing cuda so file names with patchelf
* correct so file path
* bumping version
* trying to test the wheel files as well
* removing the tests; too complicated
> using supported python versions (#357)

- spack/packages/musica/package.py
Updates the MUSICA spack script to use the latest release
> Update the MUSICA spack script

- README.md
- docs/source/tutorials/2. hypercube.ipynb
- docs/source/tutorials/4. local_parallelization.ipynb
- docs/source/tutorials/5. hpc_parallelization.ipynb
- docs/source/tutorials/6. gpu_solver.ipynb
- docs/source/tutorials/tutorials.rst
- tutorials/2. hypercube.ipynb
- tutorials/4. local_parallelization.ipynb
- tutorials/5. hpc_parallelization.ipynb
- tutorials/6. gpu_solver.ipynb
last PR temporarily set Binder links to a now-closed branch. All links updated to reference the main repository.
closes #437
> update binder links to main

- include/musica/carma/carma.hpp
- include/musica/carma/carma_c_interface.hpp
- musica/carma.cpp
- musica/carma.py
- src/carma/carma.cpp
- src/carma/carma_c_interface.cpp
- src/carma/carma_parameters.F90
- src/carma/interface.F90
- src/test/unit/carma/carma_c_api.cpp
- Moves all data processing out of fortran and into python
- removes some parameters which are not needed or used
Closes #481
> 481 move carma data processing out of fortran and into python

- include/musica/carma/carma_c_interface.hpp
- include/musica/carma/carma_state.hpp
- musica/__init__.py
- musica/carma.cpp
- musica/carma.py
- musica/test/test_carma.py
- pyproject.toml
- src/carma/carma.cpp
- src/carma/carma_state.cpp
- src/carma/interface.F90
- src/test/unit/carma/carma_c_api.cpp
- adds a destructor for carma state
- adds set_gas
- adds set_detrain
- adds set_bin
closes #485
> 485 wrap carmastate set functions

- include/musica/carma/carma_c_interface.hpp
- include/musica/carma/carma_state.hpp
- musica/carma.cpp
- src/carma/carma_parameters.F90
- src/carma/carma_state.cpp
- src/carma/interface.F90
- src/test/unit/carma/carma_c_api.cpp
Adds the ability to provide optional arguments to the `CARMASTATE_Create()` function.
> Adds optional CARMA State create options

- include/musica/carma/carma.hpp
- include/musica/carma/carma_c_interface.hpp
- musica/carma.cpp
- musica/carma.py
- musica/test/test_carma.py
- src/carma/carma.cpp
- src/carma/interface.F90
Closes #541 
I didn't add a test because I don't know what values to get, except for calling it from python which makes sure it doesn't segfault and fail
> wrapping group get

- cmake/dependencies.cmake
- src/micm/convert_v0_to_v1.cpp
- src/micm/v0_parse.cpp
- src/micm/v1_parse.cpp
This PR:
- Updates MICM tag
- Closes #380
> Use the latest tag of MICM

- README.md
Closes #628 
@mgduda pointed out last week that we do not have an explicit list of dependencies anywhere. This PR addressed that.
> adding a list of dependencies
