CMakeLists.txt
Dockerfile.fortran
musica-fortran/CMakeLists.txt
musica-fortran/test/CMakeLists.txt

I updated the files to show what I meant to describe with using the musica fortran interface.
In this scenario, musica is already installed on the machine. Someone creates a new cmake project and includes the musica fortran wrapper with fetch content and the target is linked automatically. The difference here is that the cmake files that control the building of musica are not run to create the test. Rather, the example project is built, and that itself finds the musica fortran target.

Modifications

---

.github/workflows/test.yml
CMakeLists.txt
Dockerfile.no_micm
musica/src/CMakeLists.txt

Fixes a problem with building the library without micm and adds a GH action to test this build configuration

add no-micm test and fix

---

musica-fortran/src/micm/micm_mod.F90
musica-fortran/test/test_musica_api.F90

Renamed micm module name as `musica_micm` to avoid duplicates from micm in atmospheric repo

Rename micm module name

---

fortran/micm_core.F90
fortran/test/fetch_content_integration/CMakeLists.txt
fortran/test/fetch_content_integration/test_micm_fort_api.F90

Remove test code for debugging and formatted spacing

Remove test code for debugging and formatted spacing

---

.github/workflows/fetch_content_integration.yml
docker/Dockerfile.fortran-gcc.integration
fortran/CMakeLists.txt
fortran/micm_core.F90
fortran/util.F90

Adds a compiler flag to allow unlimited line length in F90 files, and converts fortran string to c char arrays before passing them to c functions.

Fixes a bug with Fortran builds

---

fortran/test/unit/util.F90
fortran/util.F90

Modifies mapping class to provide 1-based indices from the fortran wrapper

Shift fortran indices to be 1-based

---

cmake/dependencies.cmake
fortran/CMakeLists.txt

As reported in the team slack, there were some issues related to position-independent code which were addressed by passing `-DCMAKE_Fortran_FLAGS="-fPIE"` at configure time.  This should obviate the need for that.
The following changes were also added:
* A PkgConfig-based check for `netcdfc` whenever `netcdf-fortran` was checked for, as the latter depends on the former, and if they were built statically, the build would otherwise fail due to undefined symbols.
* Updating the default `tag` for `tuv-x` to one which incorporates the fix for the same issue (position-independent code) in the tuv-x dependency.

Set musica-fortran position-independent code macro to ON when building static library

---

.clang-format

Modified regex for clang format.
The current REGEX failed to list an external header with `-` above system headers. (The example is from tuvx, which I found the failure.)
Current:
```c++: 
#include <tuvx/util/config_yaml.h>
#include <cstring>
#include <fstream>
#include <yaml-cpp/yaml.h>
```
This PR:
```c++: 
#include <tuvx/util/config_yaml.h>
#include <yaml-cpp/yaml.h>
#include <cstring>
#include <fstream>
```

Modify regex for clang format

---

fortran/micm.F90
fortran/test/fetch_content_integration/test_micm_api.F90
include/musica/micm.hpp
python/test/analytical.py
python/test/chapman.py
python/wrapper.cpp
src/micm/micm.cpp
src/test/unit/micm/micm_c_api.cpp

Add air density as an input to the solve function for MICM
closes #157

Add air density to MICM solve function as input

---

fortran/micm.F90
fortran/test/fetch_content_integration/test_get_micm_version.F90
fortran/test/fetch_content_integration/test_micm_box_model.F90
fortran/tuvx/grid.F90
fortran/tuvx/grid_map.F90
fortran/tuvx/profile.F90
fortran/tuvx/profile_map.F90
fortran/tuvx/tuvx.F90

2, 3 and 4 spacing is used for indentation. This PR uniformizes the indentation for Fortran code base with the spacing size of 2.

Uniformize the indentation for Fortran code base

---

CITATION.cff
CMakeLists.txt
cmake/dependencies.cmake
python/CMakeLists.txt
src/packaging/CMakeLists.txt

Update version for release

---

CMakeLists.txt
cmake/dependencies.cmake
fortran/micm.F90
fortran/test/fetch_content_integration/test_micm_api.F90
include/musica/micm.hpp
pyproject.toml
python/wrapper.cpp
src/micm/micm.cpp
src/test/unit/micm/micm_c_api.cpp

Closes #224
Using this version of musica in music box makes the slow example Sancy pointed out extremely fast to run, though the construction still takes about 5 seoncds
This is a temporary fix. #217 will provide an interface to the state that python could hold and use directly

Store a state alongside the solver

---

include/musica/util.hpp

Fixes a missing initialization of the pointer to the YAML parser in the `Configuration` struct

Initialize config pointer to nullptr

---

docker/Dockerfile.fortran-intel
fortran/micm.F90
fortran/test/fetch_content_integration/test_micm_api.F90
fortran/test/fetch_content_integration/test_tuvx_api.F90
fortran/tuvx/grid.F90
fortran/tuvx/profile.F90
fortran/tuvx/radiator.F90
fortran/tuvx/tuvx.F90
fortran/util.F90

Adds the `contiguous` attribute to fortran API function array arguments that are passed as C-style pointers to MUSICA library C functions. This allows strided-access array slices to be passed to these functions, but still pass contiguous-in-memory arrays to the C functions. Updates related tests to pass array slices from fortran.

Add `contiguous` attribute for arrays passed to c functions

---

cmake/dependencies.cmake
fortran/test/unit/util.F90
fortran/util.F90

Fixes the intent to be `inout` for the target data array in the `index_mapping_t::copy_data()` function and adds a test with strided-access array slices.
Also, updates the build scripts to use the latest commit on main for TUV-x

Fixes the intent of the target array in the `copy_data` function

---

fortran/test/unit/util.F90
fortran/util.F90
include/musica/util.hpp
src/test/unit/util.cpp
src/util.cpp

Adds a function that returns the number of elements in an index mappings object.

Add size function to index mappings

---

fortran/test/unit/util.F90
fortran/util.F90
include/musica/util.hpp
src/test/unit/util.cpp
src/util.cpp

Adds the ability to create index mappings that match every source-target pair in the configuration file, or only those where the source and target labels are both present in the source and target arrays.

Add map matching options

---

fortran/CMakeLists.txt
fortran/util.F90
src/CMakeLists.txt

Fixed an issue of the installed musica-fortran modules being not placed in the include path.

Fix bugs when building and linking MUSICA with MUSICA-CCPP sources

---

CMakeLists.txt
spack/packages/musica/package.py
spack/repo.yaml
src/packaging/CMakeLists.txt

This is also in support of a PR to include musica in [spack](https://github.com/spack/spack/pull/49988)
I've also removed support for module files. From what I understand, spack can [generate these automatically](https://spack-tutorial.readthedocs.io/en/latest/tutorial_modules.html).
Closes #18 
Closes #54

adding spack option

---

cmake/dependencies.cmake
fortran/micm/micm.F90
fortran/micm/state.F90

Uses the latest version of MICM and adds a function that resets the pointers to the concentration array because the solver does swaps on the `std::vector` and the Fortran State wrapper class maintains c pointers to the first array element.

Updates MICM version

---

pyproject.toml

Adds mechanism configuration as a dependency. Now, when you `pip install musica`, or `pip install -e .`, you will also get the mechanism configuration package

adding mechanism configuration as a dependency

---

musica/types.py
musica/wrapper.cpp

The chemistry object was not actually used and we take in a mechanism configuration type rather than a chemistry object. 
As a side note, since we should eventually write documentation for mechansim configuraiton, we should be able to link to that directly in the docstring using [intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html).

removes references to unused chemistry object

---

musica/test/test_chapman.py
musica/types.py

Updates the set_conditions function in the Python API to allow setting temperature, pressure, or air density with int values.

Allow ints to be passed to set conditions

---

cmake/dependencies.cmake
fortran/micm/micm.F90
fortran/micm/state.F90
fortran/test/fetch_content_integration/test_micm_api.F90
fortran/test/fetch_content_integration/test_micm_box_model.F90
include/musica/micm/micm.hpp
include/musica/micm/micm_c_interface.hpp
include/musica/micm/state.hpp
include/musica/micm/state_c_interface.hpp
musica/musica.cpp
musica/types.py
src/micm/micm_c_interface.cpp
src/micm/state.cpp
src/micm/state_c_interface.cpp
src/test/unit/micm/micm_c_api.cpp

Updates the C and Fortran APIs to correctly traverse the vector-ordered MICM matrices.
Now, there is a single user-side pattern that can be used to interact with MICM state data without specific logic for vector or standard matrix ordering. Also, updates naming and removes unneeded functions to improve the consistency across the C, Fortran, and Python APIs.
closes #272

Updates API for MICM correct vector matrix traversing

---

.github/workflows/python-wheels.yml

It turns out when building the python library with cuda support, we end up needing to include the cuda libraries in the wheel file and they are over 100MB. That is too much for pypi. [The error showing it's too large.](https://github.com/NCAR/musica/actions/runs/14937523426/job/42075150698)
This PR adds a test to make sure the cuda python build will succeed, but we will only package up the CPU code for the actual pypi release (for now).
Below lists the size of the cuda files
```
:: zipinfo musica-0.11.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Archive:  musica-0.11.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Zip file size: 419880595 bytes, number of entries: 42
drwxr-xr-x  2.0 unx        0 b- stor 25-May-09 21:04 lib64/
drwxr-xr-x  2.0 unx        0 b- …
```

testing build action

---

CMakeLists.txt
musica/CMakeLists.txt
musica/__init__.py
musica/mechanism_configuration.py
musica/test/test_analytical.py
musica/test/test_parser.py
musica/tools/repair_wheel_gpu.sh
musica/types.py

This PR restructures the python package
before, in the site packages directory we would install `lib` `_musica*.so`, and `musica`. Now, all files are under `musica`. 
I also corrected the path of the nvidia files which should be located at `../nvidia/*`, meaning relative to the `so` location. I misunderstood where this would be from before. 
I think with these changes, we may actually be able to install musica from pypi on linux. A remaining problem is that now linux users are required to install the gpu option, I think, because the `so` file requires the cuda files to be found. That's an issue I'll solve once I can verify this works. I was able to test an install from a wheel file like this on derecho:
```
pip install "musica[gpu] @ …
```

putting so file into musica folder, updating relative rpath

---

fortran/packaging/CMakeLists.txt
src/packaging/CMakeLists.txt

A case-sensitive string comparison was being used to check the CMake build type when creating the pkf-config file. This modifies the logic to use case-insensitive comparisons.

Fix case sensitive string comparison in pkgconfig generation

---

.github/workflows/format-python.yml
spack/packages/musica/package.py

Update the Spack script to use the new version of MUSICA
This is the same change that got approved in the last PR. I messed up when reverting the main branch, and the update got lost.

Update the Spack script to use the new version of MUSICA

---

docs/source/conf.py
docs/source/user_guide/configurations.rst

intersphinx extension sets up an objects.inv file to be referenced from MusicBox (and other documentation in the future). I set up links to MICM, MusicBox, and Mechanism Configuration for future reference. 
Note: I tested the existing MusicBox links to this new Musica intersphinx object on my local server and they all work. But I will still be adjusting MusicBox slightly
closes #386

add intersphinx linking to Musica

---

include/musica/carma/carma.hpp
include/musica/carma/carma_c_interface.hpp
musica/carma.cpp
musica/carma.py
src/carma/carma.cpp
src/carma/carma_parameters.F90
src/carma/interface.F90

Updates the MUSICA C and Python APIs to allow setting of all CARMA Group options. Also removes some options that can be inferred from other data (e.g., `id`, `do_mie`)
closes #470

CARMA group options

---

include/musica/carma/carma.hpp
include/musica/carma/carma_c_interface.hpp
musica/carma.cpp
musica/carma.py
src/carma/carma.cpp
src/carma/carma_parameters.F90
src/carma/interface.F90
src/test/unit/carma/carma_c_api.cpp
valgrind.supp

Wraps the `CARMA_Initialize()` function for the C and Python APIs. Also adds a few valgrind suppressions that should be removed after the `CARMASTATE_*` functions are finished.
closes #483

Add CARMA initialization options

---

README.md
binder/apt.txt
binder/requirements.txt

Binder has been updated to use an editable installation of MUSICA after cloning from main rather than a pip install so that tutorials can stay up-to-date without waiting for new release.

update Binder to reference main

---

include/musica/carma/carma_c_interface.hpp
include/musica/carma/carma_state.hpp
musica/carma.cpp
musica/carma.py
musica/test/test_carma.py
src/carma/carma_state.cpp
src/carma/interface.F90
src/test/unit/carma/carma_c_api.cpp

Adds the remaining CARMA state set functions.
Also updates the python tests to more closely mimic the C++ tests, and fixes an incorrect call to `SetBin` in the python wrapper

Add remaining CARMA set functions

---

.github/workflows/format.yml
musica/carma.py

Closes #543 
- No need to wrap `CARMASOLUTE_Get`, all of that information is specified in the solute configuration and can be returned from python directly
- Added logic to the format action to format the c++ code in the musica python library

get solute

---

musica/carma.py
musica/test/test_carma.py

closes #544 
No need to go into fortran, the information provided in the gas configuration can be returned directly

get gas config

---

include/musica/carma/error.hpp
src/carma/carma.cpp
src/carma/carma_state.cpp
src/carma/interface.F90

Closes #499
Adds an error header file whose codes are used in fortran and converted to strings in c++

499 return error messages from carma wrapper functions

---

src/carma/interface.F90

Updates calls to CARMA Fortran functions to use named arguments throughout. I checked the order of the bins and elements and they all look correct.
closes #556

Add named fortran args

---

docker/Dockerfile.python
musica/examples/sulfate_box_model.py
musica/test/unit/test_state.py
musica/types.py
src/micm/v1_parse.cpp

This PR updates the MUSICA Python API to allow optional inclusion of temperature and/or pressure in the `set_conditions()` function. If either is not included, the current temperature/pressure value remains unchanged. This will be used in MusicBox when evolving conditions are set (which may or may not need to update the temperature/pressure).
Also adds unit tests for the Python State wrapper class

Allow optional setting of temperature and pressure
